/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import Link from "next/link";
import { ActionLink } from "../../components/ActionLink";
import { PortfolioFooter } from "../../components/PortfolioFooter";
import { PortfolioHeader } from "../../components/PortfolioHeader";
import { CaseStudyHero } from "../../components/case-study/CaseStudyHero";
import { CaseStudyMedia } from "../../components/case-study/CaseStudyMedia";
import { CaseStudySection } from "../../components/case-study/CaseStudySection";
import { ContentBlockRenderer } from "../../components/case-study/ContentBlockRenderer";
import { VerticalChapterNav } from "../../components/case-study/VerticalChapterNav";
import { ComparisonTable } from "../../components/case-study/ComparisonTable";
import { InsightGrid } from "../../components/case-study/InsightGrid";
import { InterimDesignCard } from "../../components/case-study/InterimDesignCard";
import { RecommendationCard } from "../../components/case-study/RecommendationCard";
import { salesContent, type SalesMediaKey } from "../../data/sales-assessment-platform";

export const metadata: Metadata = { title: "Sales Assessment Platform AI Integration — Melissa Shi", description: "Reimagining an internal sales platform from AI-assisted automation to AI-guided collaboration." };

const chapters = [
  { id: "introduction", label: "Introduction" }, { id: "collaboration-model", label: "AI collaboration" },
  { id: "platform-expansion", label: "Platform expansion" }, { id: "product-vision", label: "Product vision" },
  { id: "outcome", label: "Outcome" }, { id: "reflection", label: "Reflection" },
];

const media = {
  thumbnail: { kind: "image", src: "/portfolio/sales-assessment-thumbnail.png", alt: "Sales Assessment Platform interface preview", width: 653, height: 453, caption: "Sales Assessment Platform AI Integration" },
  "hero-video": { kind: "video", src: "/portfolio/sales-assessment-hero.mp4", caption: "Sales Assessment Platform prototype" },
  "current-workflow": { kind: "image", src: "/portfolio/sales-assessment-current-workflow.png", alt: "Current waterfall workflow from customer information to PowerPoint", width: 1023, height: 137, caption: "The original workflow made AI an optional generation step." },
  "iteration-one": { kind: "video", src: "/portfolio/sales-assessment-iteration-one.mp4", caption: "First vision prototype presented to stakeholders" },
  "lead-with-ai": { kind: "image", src: "/portfolio/sales-assessment-lead-with-ai.png", alt: "Sales assessment workflow led by AI chat", width: 3835, height: 1970, caption: "AI leads the assessment where conversation creates value." },
  "human-review": { kind: "image", src: "/portfolio/sales-assessment-human-review.png", alt: "Editable AI recommendations before final output", width: 3835, height: 1967, caption: "Human review keeps sales representatives in control." },
  "design-system": { kind: "image", src: "/portfolio/sales-assessment-design-system.png", alt: "Cisco IT design system comparison", width: 949, height: 997, caption: "The concept was grounded in the Cisco IT design system." },
  "customer-context": { kind: "image", src: "/portfolio/sales-assessment-customer-context.png", alt: "Reusable customer context experience", width: 3792, height: 1967, caption: "Customer context is collected once and reused across assessments." },
  "gong-integration": { kind: "image", src: "/portfolio/sales-assessment-gong-integration.png", alt: "Native Gong meeting intelligence integration", width: 3827, height: 1965, caption: "Gong conversations add richer customer context." },
  "ai-copilot": { kind: "image", src: "/portfolio/sales-assessment-ai-copilot.png", alt: "AI co-pilot at a strategic decision point", width: 3805, height: 1967, caption: "AI appears when sales representatives need decision support." },
  "ai-clarification": { kind: "image", src: "/portfolio/sales-assessment-ai-clarification.png", alt: "AI clarification and conflict detection", width: 3835, height: 1970, caption: "AI asks for clarification instead of confidently producing weak output." },
  "web-output": { kind: "image", src: "/portfolio/sales-assessment-web-output.png", alt: "Web-based assessment output", width: 3832, height: 1967, caption: "A branded web experience becomes the assessment output." },
  "opportunity-link": { kind: "image", src: "/portfolio/sales-assessment-opportunity-link.png", alt: "Assessment linked to a sales opportunity", width: 3790, height: 1962, caption: "Assessments stay connected to the relevant sales opportunity." },
  "business-case-result": { kind: "image", src: "/portfolio/sales-assessment-business-case-result.png", alt: "Business case results alongside configuration", width: 3800, height: 1972, caption: "Users can see how configuration affects annual value in real time." },
  "iteration-three": { kind: "video", src: "/portfolio/sales-assessment-iteration-three.mp4", caption: "Third prototype exploring the long-term platform vision" },
  "account-context": { kind: "image", src: "/portfolio/sales-assessment-account-context.png", alt: "Layered account and assessment context", width: 3832, height: 1965, caption: "Customer context is separated into reusable account and assessment layers." },
  "web-delivery": { kind: "image", src: "/portfolio/sales-assessment-web-delivery.png", alt: "Branded customer website delivery", width: 1912, height: 905, caption: "The website becomes the living assessment delivery destination." },
  onboarding: { kind: "image", src: "/portfolio/sales-assessment-onboarding.png", alt: "Onboarding experience for building quality AI inputs", width: 3830, height: 1965, caption: "Onboarding enables stronger customer context and AI outputs." },
  "final-workflow": { kind: "image", src: "/portfolio/sales-assessment-final-workflow.png", alt: "Final end-to-end sales assessment workflow", width: 375, height: 515, caption: "The final platform vision connects context, collaboration, review, delivery, and engagement." },
} as const;

function renderMedia(key: SalesMediaKey, index: number) { return <CaseStudyMedia key={`${key}-${index}`} {...media[key]} />; }

export default function SalesAssessmentPlatformCaseStudy() {
  return <main className="case-study sales-assessment-case-study">
    <PortfolioHeader />
    <CaseStudyHero
      backLink={<Link className="case-back" href="/#selected-work">← Back to selected work</Link>}
      eyebrow="AI product design · Sales enablement"
      title="Sales Assessment Platform AI Integration"
      deck="Reimagining an internal sales platform from AI-assisted automation to AI-guided collaboration"
      overviewPanels={[{ heading: "Goal", content: <p>Help transform a legacy sales assessment platform into an AI-powered experience that accelerates assessment creation while keeping sales representatives in control.</p> }, { heading: "Outcome", content: <ul><li>Reframed the product vision from AI as an optional feature to AI as an integrated workflow partner.</li><li>Influenced AI interaction patterns across multiple assessment workflows.</li><li>Earned stakeholder buy-in through high-fidelity prototypes and expanded my role into an AI design consultant.</li></ul> }]}
      metadataItems={[{ label: "Role", value: "Design Consultant (UX Strategy, AI Interaction Design, Prototyping)" }, { label: "Timeline", value: "40 hours over 3 weeks" }, { label: "Client", value: "3 Business Value Advisors" }]}
      metadataClassName="sales-source-meta"
      mediaSlots={renderMedia("hero-video", 0)}
    />
    <VerticalChapterNav chapters={chapters} />
    <CaseStudySection id="introduction" eyebrow="01 · Introduction" title="Turning AI from a feature into a collaborator"><ContentBlockRenderer blocks={salesContent.introduction.slice(0, 10)} renderMedia={renderMedia} /><ComparisonTable headings={["Issues", "Opportunities"]} rows={[["AI appeared as an optional feature rather than a natural part of the workflow.", "Move AI from optional feature to workflow driver"], ["AI generated outputs without helping users think through the problem.", "Design AI as a co-pilot, not a one-time generator"], ["Generated content became a dead end if it wasn't immediately usable.", "Blend AI generation with manual control"], ["PowerPoint outputs still required significant manual cleanup.", "Adapt for versatile assessment output format"], ["The prototype's UI wasn't aligned with Cisco's design system.", "Use the Cisco IT design system"]]} /><h3>My Design Principles</h3><p>Rather than asking "Where can we add AI?"</p><p>I reframed the problem as:</p><ContentBlockRenderer blocks={[salesContent.introduction[16]]} renderMedia={renderMedia} /><InsightGrid mode="insights" groups={["🤝 AI should guide—not replace—users", "🧠 Collect context once and reuse it throughout the workflow", "✏️ AI outputs should always remain editable", "💬 Use conversation only when conversation creates value", "📈 Outputs should continue generating value after they're created"].map((text) => <p key={text}>{text}</p>)} /></CaseStudySection>
    <CaseStudySection id="collaboration-model" eyebrow="02 · AI collaboration model" title="Selling a new vision" tone="pink"><ContentBlockRenderer blocks={salesContent.collaboration.slice(0, 4)} renderMedia={renderMedia} /><h3>Vision Details</h3><p>Instead of redesigning individual screens, I focused on changing the product's interaction model.</p><InterimDesignCard sequence={1} title="Leading with AI Chat" media={renderMedia("lead-with-ai", 0)}><h5>Before</h5><p>AI appeared as another button users could optionally click.</p><h5>After</h5><p>AI appeared at the front of the workflow to make AI feel like the primary way to begin an assessment and encourage users to leverage the efficiency of AI assistance.</p><h5>Opportunity</h5><p>Not every assessment type is best suited for a chat-first experience. In some contexts, manual controls may be more efficient than open-ended conversation.</p><p>This feedback helped refine the strategy: AI should not replace structured workflows. It should appear where conversation, guidance, or synthesis creates real value.</p></InterimDesignCard><InterimDesignCard sequence={2} title="Human Review Before Final Output" media={renderMedia("human-review", 1)}><h5>Before</h5><p>AI generated final PowerPoint slides immediately after receiving meeting notes.</p><h5>After</h5><p>AI first produced editable recommendations that sales representatives could review, refine, and approve before generating customer-facing deliverables.</p><p>This kept humans accountable while letting AI remove repetitive work.</p></InterimDesignCard><InterimDesignCard sequence={3} title="Cisco Design System" media={renderMedia("design-system", 2)}><h5>Before</h5><p>The original prototype relied heavily on AI-generated styling.</p><h5>After</h5><p>I redesigned the experience using the Cisco IT Design System to create:</p><ul><li>familiar internal experiences</li><li>development consistency</li><li>reduced implementation effort</li><li>enterprise credibility</li></ul></InterimDesignCard><ContentBlockRenderer blocks={salesContent.collaboration.slice(-7)} renderMedia={renderMedia} /></CaseStudySection>
    <CaseStudySection id="platform-expansion" eyebrow="03 · Platform expansion" title="Expanding AI across the platform"><p>Once stakeholders aligned on the overall direction, we explored where AI could create the most value across the product.</p>{renderMedia("hero-video", 3)}<h3>Design Details</h3>{[["Customer Context as the Foundation", "Sales representatives repeatedly entered customer information throughout different assessments. I redesigned the home experience around reusable customer context.", "customer-context"], ["Native Gong Integration for Meeting Intelligence", "Instead of manually downloading transcripts and uploading files, the platform could pull customer conversations directly from Gong. This eliminated unnecessary work while improving AI's understanding of customer needs.", "gong-integration"], ["AI Co-pilot at Decision Points", "Rather than displaying a permanent chat window, AI appeared only when users needed help making strategic decisions. Such as shaping the sales narrative and refining talking points. The interaction became purposeful instead of distracting.", "ai-copilot"], ["AI Clarification and Conflict Detection", "Instead of confidently generating weak outputs from incomplete information, AI proactively asked follow-up questions and clarifications. These clarification moments increased trust while improving output quality.", "ai-clarification"], ["Web-Based Assessment Outputs", "Instead of producing another PowerPoint deck, I explored generating branded web experiences. This unlocked flexible layouts, richer storytelling, easier sharing, customer engagement analytics, and visibility into what customers actually viewed.", "web-output"]].map(([title, text, key], index) => <RecommendationCard key={title} sequence={index + 1} segments={[<div className="feedback-blocks" key="copy"><h4>{title}</h4><p>{text}</p></div>, renderMedia(key as SalesMediaKey, index + 4)]} />)}<h3>Additional Design Enhancements</h3><p>Beyond the core AI workflow, I also proposed</p><RecommendationCard sequence={6} segments={[<div className="feedback-blocks" key="opportunity"><h4>Linking assessments directly with sales opportunities</h4><p>Each assessment is connected to the right opportunity context, making the platform easier to organize, track, and analyze over time.</p></div>, renderMedia("opportunity-link", 9)]} /><RecommendationCard sequence={7} segments={[<div className="feedback-blocks" key="business"><h4>Placing business case results on the same level as business case configuration</h4><p>User can see in real-time how configuration affects business case annual value.</p></div>, renderMedia("business-case-result", 10)]} /></CaseStudySection>
    <CaseStudySection id="product-vision" eyebrow="04 · Long-term vision" title="Defining the long-term product vision" tone="pink"><ContentBlockRenderer blocks={salesContent.vision} renderMedia={renderMedia} /></CaseStudySection>
    <CaseStudySection id="outcome" eyebrow="05 · Outcome" title="From vision to adoption"><InsightGrid mode="outcomes" groups={[["Vision to Adoption", "Team adopted my proposal and started implementing: Lead with AI Chat, Customer context, Opportunity linking, AI chat, Results Website, and Cisco IT design system."], ["Product", "Reframed SVP from AI-assisted automation to AI-guided collaboration."], ["User Experience", "Designed interaction patterns that balanced AI efficiency with human judgment, review, and control."], ["AI Strategy", "Moved the experience beyond generic content generation by grounding AI outputs in reusable customer context, stakeholder profiles, and meeting intelligence."], ["Business", "Expanded assessment outputs beyond PowerPoint into branded, trackable, web-centered customer experiences."], ["Stakeholders", "Earned stakeholder buy-in through rapid prototyping and expanded my engagement from design feedback into ongoing AI product consulting."]].map(([title, text]) => <><h4>{title}</h4><p>{text}</p></>)} /><ContentBlockRenderer blocks={salesContent.outcome.slice(-2)} renderMedia={renderMedia} /></CaseStudySection>
    <CaseStudySection id="reflection" eyebrow="06 · Reflection" title="Designing an AI collaboration platform" tone="pink"><ContentBlockRenderer blocks={salesContent.reflection} renderMedia={renderMedia} /></CaseStudySection>
    <section className="case-next case-shell"><p className="eyebrow">Keep exploring</p><h2>See more work where research shapes product strategy.</h2><ActionLink href="/#selected-work">Back to selected work</ActionLink></section>
    <PortfolioFooter />
  </main>;
}
